load("@apex//tools/bazel/rules_ros_pkg:defs.bzl", "ros_pkg")

cc_library(
    name = "aws_crt_cpp",
    srcs = glob(
        ["source/**/*.cpp"],
    ),
    hdrs = glob(
        ["include/aws/**/*.h"],
    ),
    copts = select({
        "@apex//common/build_system_transfer:enabled": ["-Wno-error=missing-field-initializers"],
        "//conditions:default": [],
    }),
    includes = ["."],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "@aws_c_auth",
        "@aws_c_cal",
        "@aws_c_common",
        "@aws_c_event_stream",
        "@aws_c_http",
        "@aws_c_io",
        "@aws_c_mqtt",
        "@aws_c_s3",
        "@aws_c_sdkutils",
    ],
)

ros_pkg(
    name = "aws_crt_cpp_pkg",
    bst_substitute_with = select({
        "@apex//common/build_system_transfer:use_cmake_find_package": {
            "name": "aws-crt-cpp",
            "cmake_find_package": """\
find_package(aws-crt-cpp REQUIRED)
if (NOT TARGET {pkg_name}::aws_crt_cpp)
    add_library({pkg_name}::aws_crt_cpp ALIAS AWS::aws-crt-cpp)
endif()
""",
        },
        "//conditions:default": {
        },
    }),
    cc_libraries = [":aws_crt_cpp"],
    description = "C++ wrapper around the aws-c-* libraries. Provides Cross-Platform Transport " +
                  "Protocols and SSL/TLS implementations for C++.",
    license = "Apex.AI Proprietary License",
    maintainer_email = "support@apex.ai",
    maintainer_name = "Apex.AI",
    pkg_name = "aws_crt_cpp_vendor",
    version = "0.26.6",
    visibility = ["//visibility:public"],
    deps = [
        "@aws_c_auth//:aws_c_auth_pkg",
        "@aws_c_cal//:aws_c_cal_pkg",
        "@aws_c_common//:aws_c_common_pkg",
        "@aws_c_event_stream//:aws_c_event_stream_pkg",
        "@aws_c_http//:aws_c_http_pkg",
        "@aws_c_io//:aws_c_io_pkg",
        "@aws_c_mqtt//:aws_c_mqtt_pkg",
        "@aws_c_s3//:aws_c_s3_pkg",
        "@aws_c_sdkutils//:aws_c_sdkutils_pkg",
    ],
)
